# Generated by Django 4.2.2 on 2023-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_edu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="profile_id",
            field=models.IntegerField(default=""),
        ),
    ]
